/**
 * User-facing language for the team workspace.
 * Keep tone warm, clear, and jargon-light — everyone reads this.
 */

export const brand = {
  /** Short name in sidebar / login */
  short: 'Team space',
  /** Full product name */
  full: 'NerdzFactory Team space',
  metaDescription:
    'Plan your work, share weekly updates, request time off, and stay in the loop with your colleagues — all in one place.',
  /** Aligns with nerdzfactory.co hero */
  tagline: 'Innovation · Development · Technology',
  headOffice:
    'Head office: 2, Insha Allah close, Off Ramat Crescent, Ogudu GRA, Ojota, Lagos.',
} as const

/** Side nav & mobile bar — keep concise */
export const nav = {
  home: 'Home',
  myWork: 'My work',
  weeklyUpdate: 'Weekly update',
  gettingStarted: 'Getting started',
  updates: 'Updates',
  timeOff: 'Time off',
  people: 'People',
  resources: 'Resources',
  shoutOuts: 'Shout-outs',
  whatsOn: "What's on",
  workspaceAdmin: 'Workspace admin',
  inbox: 'Inbox',
  search: 'Search',
  notes: 'Notes',
} as const

/** How we describe roles on profile cards, headers, etc. */
export const roleTitles = {
  staff: 'Team member',
  team_lead: 'People lead',
  hr: 'People & culture',
  admin: 'Workspace admin',
} as const

/** Common actions */
export const actions = {
  save: 'Save',
  cancel: 'Cancel',
  close: 'Close',
  signIn: 'Sign in',
  signOut: 'Sign out',
  viewAll: 'View all',
  learnMore: 'Learn more',
} as const

export const pages = {
  login: {
    title: 'Welcome back',
    subtitle: 'Sign in to your NerdzFactory team workspace.',
    demoHint: 'Try a demo account below, then tap Sign in.',
    emailLabel: 'Work email',
    passwordLabel: 'Password',
  },
  home: {
    title: 'Home',
    subtitle:
      'Your week at a glance — deadlines, time off, company updates, and what’s on today.',
    roleLine: (jobTitle: string, department: string) => `${jobTitle} · ${department}`,
    quickAddTask: 'New task',
    quickTimeOff: 'Request time off',
    quickWeekly: 'Weekly update',
    stats: {
      dueToday: 'Due today',
      dueTodayHint: 'Open tasks with today’s date',
      pendingTimeOff: 'Time off in review',
      pendingTimeOffHint: 'Waiting on approval',
      eventsThisWeek: 'This week',
      eventsThisWeekHint: 'Meetings & gatherings in the next 7 days',
      newUpdates: 'New updates',
      newUpdatesHint: 'Company posts you haven’t opened yet',
    },
    onboardingBanner: (watched: number, total: number) =>
      `You’ve completed ${watched} of ${total} welcome videos`,
    onboardingCta: 'Continue learning',
    recentUpdates: 'Latest updates',
    todaySchedule: 'Today',
    emptyUpdates: 'No updates yet',
    emptyUpdatesBody: 'When your People & culture team posts news, it’ll show up here.',
    emptyDay: 'Nothing scheduled',
    emptyDayBody: 'Enjoy the calm — or add something in What’s on.',
    tipTitle: 'Small habits help the team',
    tipBody:
      'Sending your weekly update on time keeps leads informed. Requesting time off here (instead of chat) gives everyone a clear record.',
  },
  tasks: {
    title: 'My work',
    subtitle:
      'Track what you’re doing, what’s blocked, and what’s due — switch between board and week views anytime.',
    board: 'Board',
    week: 'Week',
    list: 'List',
    filterScope: 'Focus',
    scopeRelated: 'Owned & assigned',
    scopeOwned: 'I own',
    scopeAssigned: 'Assigned to me',
    newTask: 'New task',
    searchPlaceholder: 'Search by title or notes…',
    filterStatus: 'Status',
    filterPriority: 'Priority',
    sortBy: 'Sort',
    sortDueSoon: 'Due date (soonest first)',
    sortDueLater: 'Due date (latest first)',
    sortUpdated: 'Recently updated',
    statusAll: 'All statuses',
    priorityAll: 'All priorities',
    clearFilters: 'Clear filters',
    statusUpNext: 'Up next',
    statusInProgress: 'In progress',
    statusComplete: 'Complete',
    statusStuck: 'Stuck',
    priorityUrgent: 'Urgent',
    priorityNormal: 'Normal',
    priorityLater: 'When you can',
    blockedHelp: 'What’s blocking you',
    blockersPlaceholder: 'Anything we should know?',
    updateStatus: 'Move to…',
    detailChangeStatus: 'Change status',
    statTotal: 'All items',
    statInProgress: 'In progress',
    statDone: 'Complete',
    statOverdue: 'Past due',
    showingCount: 'Showing {n} of {total} items',
    columnEmpty: 'Nothing here yet',
    filteredEmptyTitle: 'Nothing matches',
    filteredEmptyBody: 'Try clearing filters or changing your search.',
    prevWeek: 'Previous week',
    nextWeek: 'Next week',
    thisWeekLabel: 'This week',
    jumpToThisWeek: 'Jump to this week',
    weekNoItems: 'Nothing due',
    formEditTitle: 'Edit item',
    formNewTitle: 'New item',
    formTitleLabel: 'Title',
    formTitlePlaceholder: 'What needs to get done?',
    formDescriptionLabel: 'Notes',
    formDescriptionPlaceholder: 'Optional — context, steps, links, or @mention someone',
    formAssigneeLabel: 'Assigned to',
    assigneeOwnerOnly: 'Owner (me, if new)',
    mentionHint: 'Tip: type @FirstName in notes to ping teammates.',
    listOverdue: 'Overdue',
    listDueToday: 'Due today',
    listThisWeek: 'Later this week',
    listLater: 'After this week',
    listNoDue: 'No due date',
    formStatusLabel: 'Status',
    formPriorityLabel: 'Priority',
    formCategoryLabel: 'Category',
    formDueLabel: 'Due date',
    formHoursLabel: 'Hours logged',
    formEstimateLabel: 'Estimated hours',
    detailDescription: 'Notes',
    detailBlockers: 'Blockers',
    detailActivity: 'Activity',
    detailHoursLogged: 'Hours logged',
    detailEstimated: 'Estimated',
    prioritySuffix: 'priority',
    deleteConfirm: 'Delete this item?',
    delete: 'Delete',
    edit: 'Edit',
    emptyTasksTitle: 'Nothing here yet',
    emptyTasksBody: 'Add something to track what you’re working on.',
    tableTask: 'Item',
    tableStatus: 'Status',
    tableCategory: 'Category',
    tableAssignee: 'Assignee',
    tableDue: 'Due',
    tableHours: 'Hours',
    saveChanges: 'Save changes',
    createTask: 'Create',
    noDue: 'No due date',
  },
  inbox: {
    title: 'Inbox',
    subtitle: 'Shout-outs, assignments, and mentions in one place.',
    markAllRead: 'Mark all read',
    empty: 'You’re all caught up',
    emptyBody:
      'When someone shouts you out, assigns you a task, or @mentions you in notes, it will show up here.',
  },
  search: {
    title: 'Search',
    subtitle: 'Find people, company updates, and tasks you have access to.',
    placeholder: 'Search people, updates, tasks…',
    people: 'People',
    updates: 'Updates',
    tasks: 'Tasks',
    noResults: 'No matches',
    hint: 'Try another name, keyword, or task title.',
  },
  notes: {
    title: 'Workspace notes',
    subtitle:
      'Notion-style pages with blocks, nested pages, and sharing — live sync when Realtime is enabled.',
    newNote: 'New page',
    allNotes: 'Pages',
    titleLabel: 'Title',
    bodyLabel: 'Note',
    bodyPlaceholder: 'Type here — teammates see updates when Supabase Realtime is enabled.',
    emptyTitle: 'Pick or create a page',
    emptyBody:
      'Write specs, meeting notes, and runbooks. Add sub-pages, blocks, and share with teams, departments, or individuals.',
    emptyList: 'No pages yet',
    delete: 'Delete',
    deleteConfirm: 'Delete this page for everyone who has access?',
    alsoHere: 'Also editing:',
    footerHint: 'Last edited by',
    sharedLabel: 'Sharing',
    share: 'Share',
    shareViewOnly: 'View sharing & copy link',
    shareReadOnlyHint:
      'You can review who has access and copy a share link below. To change settings, you must be the page owner (or an admin).',
    shareLinkToPage: 'Link to this page',
    shareLinkCopyHelp: 'Send this URL to someone who should open this page. They must sign in; the key in the link grants access here.',
    shareNoLinkActive:
      'No share link is turned on yet, so there is no URL to copy. Ask the page owner to open Share, enable link sharing, then copy the link from there.',
    sharePageOwner: 'Page owner',
    shareInvitedEmailsList: 'Email invites',
    shareClose: 'Close',
    shareTitle: 'Share page',
    shareIntro: 'Choose who can open this page. The page owner (or an admin) can change these settings.',
    shareWho: 'Who has access',
    shareCancel: 'Cancel',
    shareSave: 'Apply',
    scopePrivate: 'Private (only me)',
    scopeWorkspace: 'Whole workspace',
    scopeDepartments: 'Specific departments',
    scopeTeams: 'Specific teams',
    scopePeople: 'Specific people',
    sharePrivate: 'Only you',
    shareWorkspace: 'Everyone in the workspace',
    sharePickDept: 'Pick at least one department',
    sharePickTeam: 'Pick at least one team',
    sharePickPeople: 'Pick at least one person',
    sharePeopleCount: 'people',
    departmentsPick: 'Departments',
    teamsPick: 'Teams',
    peoplePick: 'People',
    shareInviteEmails: 'Invite by email',
    shareInviteEmailsHint:
      'Anyone with these emails can view this page when they sign in with a matching account.',
    shareInvitePlaceholder: 'name@company.com',
    shareInviteAdd: 'Add',
    shareLinkSection: 'Link sharing',
    shareLinkHelp:
      'Turn on a secret link. Anyone with the URL can view the page in this browser workspace (they still sign in for other areas).',
    shareLinkOn: 'Link on',
    shareLinkOff: 'Link off',
    shareLinkCopy: 'Copy link',
    shareLinkRegenerate: 'New link key',
    shareLinkCopied: 'Copied',
    invitedEmails: 'email invites',
    blockMenuTitle: 'Turn into…',
    mentionMenuLabel: 'People',
    mentionEmpty: 'No matching people',
    emojiPickerTitle: 'Pick an icon',
    gripHint: 'Drag to reorder',
    notionHint: 'Pages',
    subPage: 'Add page',
    addBlock: 'Insert',
    blockType: 'Block type',
    removeBlock: 'Remove block',
    blockPh: "Write, or type '/' for blocks…",
    headingPh: 'Heading',
    calloutPh: 'Callout text',
    iconLabel: 'Icon',
    untitledPlaceholder: 'Untitled',
    slashHint: "Type '/' to open the block menu — filter with letters (e.g. /h2, /todo).",
    slashMenuLabel: 'Block types',
    slashMenuSection: 'Blocks',
    openBlockMenu: 'Block menu',
    todoDoneLabel: 'Done',
    todoCompletedOn: 'Completed',
    remoteNoteTitle: 'This page was updated by someone else',
    remoteNoteBody: 'Load their version to continue together, or keep editing to save your changes.',
    remoteNoteLoadLatest: 'Load latest',
    remoteNoteDismiss: 'Dismiss',
    addBlockBelow: 'Add block',
    appendBlock: 'Add a block',
    iconPrompt: 'Paste or type an emoji for this page',
    statusLive: 'Team live',
    statusConnecting: 'Connecting…',
    statusLocalTabs: 'This browser only',
    statusError: 'Realtime error',
    statusSolo: 'Offline collaboration',
    supabaseHint:
      'Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to enable live edits and presence with your team. Until then, notes are saved in this browser and sync across your tabs only.',
  },
  weeklyUpdate: {
    title: 'Weekly update',
    subtitle:
      'A quick reflection each week helps your lead support you and keeps priorities visible. Most people send this on Friday.',
    tabThisWeek: 'This week',
    tabHistory: 'Past updates',
    tabTeam: 'Team’s updates',
    submittedTitle: 'Thanks — you’re all set',
    editButton: 'Edit my update',
  },
  gettingStarted: {
    title: 'Getting started',
    subtitle: 'Videos and a simple checklist so your first weeks feel less overwhelming.',
    tabVideos: 'Videos',
    tabChecklist: 'Checklist',
    tabAdmin: 'Manage content',
  },
  updates: {
    title: 'Updates',
    subtitle: 'News and notes from leadership and People & culture — newest first.',
    newPost: 'New update',
    searchPlaceholder: 'Search updates…',
    markAllRead: 'Mark all as read',
    unreadOnly: 'Unread only',
    priorityFYI: 'FYI',
    priorityHeadsUp: 'Heads up',
    priorityAction: 'Action needed',
    priorityAll: 'All levels',
    priorityFilterLabel: 'Urgency',
    openedCount: '{n} opened',
    everyone: 'Everyone',
    unknownAuthor: 'Unknown',
    emptyFilteredTitle: 'Nothing matches',
    emptyFilteredBody: 'Try a different search or clear the filter.',
    emptyFeedTitle: 'No updates yet',
    emptyFeedBodyPoster: 'Share the first post when you’re ready.',
    emptyFeedBodyMember:
      'When People & culture or your leads share news, it’ll show up here.',
    formNewTitle: 'New update',
    formEditTitle: 'Edit update',
    formTitleLabel: 'Title',
    formTitlePlaceholder: 'Short, clear headline',
    formBodyLabel: 'Message',
    formBodyPlaceholder: 'What’s changing, what people should know, and any ask.',
    formAudienceLabel: 'Who should see this',
    formPriorityLabel: 'How urgent is this',
    deleteConfirm: 'Delete this update?',
    editAria: 'Edit update',
    deleteAria: 'Delete update',
  },
  timeOff: {
    title: 'Time off',
    subtitle: 'See your balances, send a request, and track approvals in one place.',
    requestCta: 'New request',
    balancesExplainer:
      'Balances are illustrative for this preview — they count approved days in the current year. Your real policy lives with People & culture.',
  },
  people: {
    title: 'People',
    subtitle:
      'Your org directory for NerdzFactory — find owners, skills, and reporting lines, then reach people on their work email. Matches how we present ourselves publicly: useful products, clear communication, one team.',
    searchPlaceholder: 'Search by name, email, role, department, or skill…',
    allDepartments: 'All departments',
    directoryNote:
      'Profiles show workspace access only. For company switchboard and HQ address, see nerdzfactory.co.',
    presenceNote:
      'Green, amber, red, and violet dots show availability when Supabase Realtime is enabled (see .env.example). Otherwise everyone appears offline except your own status.',
    sendEmail: 'Send email',
    copyEmail: 'Copy address',
    copied: 'Copied',
    openProfile: 'Profile',
    organization: 'Organization',
    reportsTo: 'Reports to',
    workLocation: 'Work location',
    accessRole: 'Workspace access',
    memberSince: 'Member since',
    about: 'About',
    skills: 'Skills',
    contact: 'Contact',
    pronouns: 'Pronouns',
    linkedin: 'LinkedIn',
    noMatches: 'No matches',
    noMatchesHint: 'Try another search or choose a different department.',
    editProfile: 'Edit my profile',
    emailSubject: (firstName: string) => `${firstName} — message from Team space`,
    emailBody: (recipientFirst: string, senderName: string) =>
      `Hi ${recipientFirst},\n\n\n— ${senderName}`,
  },
  resources: {
    title: 'Resources',
    subtitle: 'Handbooks, templates, brand files, and guides your team shares here.',
    upload: 'Upload a file',
  },
  shoutOuts: {
    title: 'Shout-outs',
    subtitle: 'Celebrate teammates — a few words go a long way.',
    give: 'Give a shout-out',
  },
  whatsOn: {
    title: 'What’s on',
    subtitle: 'Team meetings, all-hands, and events that matter to you.',
    newEvent: 'Add event',
    list: 'List',
    calendar: 'Calendar',
    schedule: 'Schedule',
    google: 'Google Calendar',
    googleTabIntro:
      'This view embeds your team’s public Google Calendar. The URL is set by your workspace admin in environment configuration.',
    externalSyncError: 'Could not load synced calendar events. Check the server feed URL.',
    externalBadge: 'Synced',
    scheduleInteractHint:
      'Click a day or drag across dates to add an event. Switch to Week or Day to pick times. Hover events for times; click for details.',
    scheduleViewHint:
      'Use Month, Week, Day, or Agenda in the toolbar. Hover an event for its time; click for details. Click a day number to jump to that day.',
  },
  workspaceAdmin: {
    title: 'Workspace admin',
    subtitle:
      'People access, company updates, time off, welcome content, and weekly summaries — for People leads and workspace admins.',
    sections: {
      people: 'People & access',
      updates: 'All updates',
      timeOff: 'Time off',
      onboarding: 'Welcome content',
      weeklyDigest: 'Weekly updates digest',
    },
  },
} as const

export const layout = {
  sidebarBadge: 'Team space',
  sidebarFootnote: (version: string) => `${version} · For team members`,
  authFooter: (year: number) => `© ${year} NerdzFactory · Team workspace`,
} as const
