/** Auto-generated by scripts/build-assignments.mjs — do not edit by hand */
import type { Assignment } from '@/types'

export const generatedAssignments: Assignment[] = [
  {
    "id": "worksheet-01-fashion-design-tailoring",
    "title": "Fashion Design & Tailoring",
    "description": "Fashion Design and Tailoring means using fabric, thread, and tools to create, cut, and sew clothing that fits well and looks good.",
    "sortOrder": 1,
    "published": true,
    "questions": [
      {
        "id": "master_name",
        "label": "Your master's name",
        "type": "text",
        "required": false,
        "section": "About you"
      },
      {
        "id": "q1_definition",
        "label": "In your own words, explain what Fashion Design & Tailoring means. Why does it matter to do it well?",
        "type": "textarea",
        "required": true,
        "section": "Definition",
        "context": "Fashion Design and Tailoring means using fabric, thread, and tools to create, cut, and sew clothing that fits well and looks good."
      },
      {
        "id": "q2a_skills_checked",
        "label": "Which of these skills do you already practise in your workshop? Select all that apply.",
        "type": "checkbox",
        "required": false,
        "options": [
          "Taking Measurements",
          "Pattern Making & Cutting",
          "Machine & Hand Sewing",
          "Finishing & Pressing"
        ],
        "section": "Technical skills"
      },
      {
        "id": "q2b_skill_practice",
        "label": "Choose ONE skill you selected above and describe exactly how you do it in your workshop.",
        "type": "textarea",
        "required": true,
        "section": "Technical skills"
      },
      {
        "id": "q3_scenario",
        "label": "What is your answer? Name the skill that failed and explain what the correct approach should be.",
        "type": "textarea",
        "required": true,
        "section": "Apply your knowledge",
        "context": "A customer comes back with a dress that does not fit, the waist is 3cm too tight. What skill went wrong, and what would you do differently next time?"
      },
      {
        "id": "q4_safety",
        "label": "Why is it important to clean and store your sewing needles and pins carefully after each use?",
        "type": "textarea",
        "required": true,
        "section": "Safety & hygiene"
      },
      {
        "id": "q4_confidence",
        "label": "How confident are you with the safety practices in your trade right now?",
        "type": "radio",
        "required": false,
        "options": [
          "Not confident at all: I need to learn more",
          "Somewhat confident: I know the basics",
          "Confident: I practise safety consistently",
          "Very confident: I can teach others"
        ],
        "section": "Safety & hygiene"
      },
      {
        "id": "q5a_commitment",
        "label": "Name ONE specific skill you will work on this week.",
        "type": "textarea",
        "required": true,
        "section": "My commitment"
      },
      {
        "id": "q5b_improvement",
        "label": "How will you know you have improved? What will be different in your work?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      },
      {
        "id": "q5c_cross_trade",
        "label": "Which skill from another trade area surprised or impressed you today?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      }
    ]
  },
  {
    "id": "worksheet-02-shoe-making",
    "title": "Shoe Making",
    "description": "Shoe Making is the skill of cutting leather or fabric, shaping it over a last (a foot-shaped mould), and joining the parts together to make footwear that is strong and comfortable.",
    "sortOrder": 2,
    "published": true,
    "questions": [
      {
        "id": "master_name",
        "label": "Your master's name",
        "type": "text",
        "required": false,
        "section": "About you"
      },
      {
        "id": "q1_definition",
        "label": "In your own words, explain what Shoe Making means. Why does it matter to do it well?",
        "type": "textarea",
        "required": true,
        "section": "Definition",
        "context": "Shoe Making is the skill of cutting leather or fabric, shaping it over a last (a foot-shaped mould), and joining the parts together to make footwear that is strong and comfortable."
      },
      {
        "id": "q2a_skills_checked",
        "label": "Which of these skills do you already practise in your workshop? Select all that apply.",
        "type": "checkbox",
        "required": false,
        "options": [
          "Pattern Cutting",
          "Lasting (Shaping the Upper)",
          "Stitching & Gluing",
          "Finishing & Polishing"
        ],
        "section": "Technical skills"
      },
      {
        "id": "q2b_skill_practice",
        "label": "Choose ONE skill you selected above and describe exactly how you do it in your workshop.",
        "type": "textarea",
        "required": true,
        "section": "Technical skills"
      },
      {
        "id": "q3_scenario",
        "label": "What is your answer? Name the skill that failed and explain what the correct approach should be.",
        "type": "textarea",
        "required": true,
        "section": "Apply your knowledge",
        "context": "A customer returns a pair of shoes after one week, the sole is already peeling off. Which skill failed, and what is the correct way to do that step?"
      },
      {
        "id": "q4_safety",
        "label": "What safety precautions should you take when using a skiving knife or sharp cutting tool in the workshop?",
        "type": "textarea",
        "required": true,
        "section": "Safety & hygiene"
      },
      {
        "id": "q4_confidence",
        "label": "How confident are you with the safety practices in your trade right now?",
        "type": "radio",
        "required": false,
        "options": [
          "Not confident at all: I need to learn more",
          "Somewhat confident: I know the basics",
          "Confident: I practise safety consistently",
          "Very confident: I can teach others"
        ],
        "section": "Safety & hygiene"
      },
      {
        "id": "q5a_commitment",
        "label": "Name ONE specific skill you will work on this week.",
        "type": "textarea",
        "required": true,
        "section": "My commitment"
      },
      {
        "id": "q5b_improvement",
        "label": "How will you know you have improved? What will be different in your work?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      },
      {
        "id": "q5c_cross_trade",
        "label": "Which skill from another trade area surprised or impressed you today?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      }
    ]
  },
  {
    "id": "worksheet-03-nail-technology",
    "title": "Nail Technology",
    "description": "Nail Technology is the skill of caring for, decorating, and treating fingernails and toenails using professional tools, products, and hygiene practices.",
    "sortOrder": 3,
    "published": true,
    "questions": [
      {
        "id": "master_name",
        "label": "Your master's name",
        "type": "text",
        "required": false,
        "section": "About you"
      },
      {
        "id": "q1_definition",
        "label": "In your own words, explain what Nail Technology means. Why does it matter to do it well?",
        "type": "textarea",
        "required": true,
        "section": "Definition",
        "context": "Nail Technology is the skill of caring for, decorating, and treating fingernails and toenails using professional tools, products, and hygiene practices."
      },
      {
        "id": "q2a_skills_checked",
        "label": "Which of these skills do you already practise in your workshop? Select all that apply.",
        "type": "checkbox",
        "required": false,
        "options": [
          "Sanitation & Hygiene",
          "Nail Preparation",
          "Gel & Acrylic Application",
          "Nail Art & Design"
        ],
        "section": "Technical skills"
      },
      {
        "id": "q2b_skill_practice",
        "label": "Choose ONE skill you selected above and describe exactly how you do it in your workshop.",
        "type": "textarea",
        "required": true,
        "section": "Technical skills"
      },
      {
        "id": "q3_scenario",
        "label": "What is your answer? Name the skill that failed and explain what the correct approach should be.",
        "type": "textarea",
        "required": true,
        "section": "Apply your knowledge",
        "context": "A client's gel nails lift and peel after just 4 days. She is upset and wants a refund. Based on what you learned today, what most likely caused this problem?"
      },
      {
        "id": "q4_safety",
        "label": "A client has a small cut on one of her fingers. What should you do before starting her nail service?",
        "type": "textarea",
        "required": true,
        "section": "Safety & hygiene"
      },
      {
        "id": "q4_confidence",
        "label": "How confident are you with the safety practices in your trade right now?",
        "type": "radio",
        "required": false,
        "options": [
          "Not confident at all: I need to learn more",
          "Somewhat confident: I know the basics",
          "Confident: I practise safety consistently",
          "Very confident: I can teach others"
        ],
        "section": "Safety & hygiene"
      },
      {
        "id": "q5a_commitment",
        "label": "Name ONE specific skill you will work on this week.",
        "type": "textarea",
        "required": true,
        "section": "My commitment"
      },
      {
        "id": "q5b_improvement",
        "label": "How will you know you have improved? What will be different in your work?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      },
      {
        "id": "q5c_cross_trade",
        "label": "Which skill from another trade area surprised or impressed you today?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      }
    ]
  },
  {
    "id": "worksheet-04-arts-crafts",
    "title": "Arts & Crafts",
    "description": "Arts and Crafts covers creating handmade items, beads, Aso-Oke fabric, bags, and Tie & Dye, using local materials, colour, and pattern to produce items that are beautiful and well-made.",
    "sortOrder": 4,
    "published": true,
    "questions": [
      {
        "id": "master_name",
        "label": "Your master's name",
        "type": "text",
        "required": false,
        "section": "About you"
      },
      {
        "id": "q1_definition",
        "label": "In your own words, explain what Arts & Crafts means. Why does it matter to do it well?",
        "type": "textarea",
        "required": true,
        "section": "Definition",
        "context": "Arts and Crafts covers creating handmade items, beads, Aso-Oke fabric, bags, and Tie & Dye, using local materials, colour, and pattern to produce items that are beautiful and well-made."
      },
      {
        "id": "q2a_skills_checked",
        "label": "Which of these skills do you already practise in your workshop? Select all that apply.",
        "type": "checkbox",
        "required": false,
        "options": [
          "Design & Pattern Planning",
          "Colour Mixing (Tie & Dye)",
          "Bead Threading & Knot Work",
          "Quality Finishing"
        ],
        "section": "Technical skills"
      },
      {
        "id": "q2b_skill_practice",
        "label": "Choose ONE skill you selected above and describe exactly how you do it in your workshop.",
        "type": "textarea",
        "required": true,
        "section": "Technical skills"
      },
      {
        "id": "q3_scenario",
        "label": "What is your answer? Name the skill that failed and explain what the correct approach should be.",
        "type": "textarea",
        "required": true,
        "section": "Apply your knowledge",
        "context": "A customer ordered a tie-dye fabric in deep blue and orange. When you finish the piece, the blue has faded to grey and the orange looks yellow. What went wrong?"
      },
      {
        "id": "q4_safety",
        "label": "What should you do to protect your hands and clothing when working with fabric dye?",
        "type": "textarea",
        "required": true,
        "section": "Safety & hygiene"
      },
      {
        "id": "q4_confidence",
        "label": "How confident are you with the safety practices in your trade right now?",
        "type": "radio",
        "required": false,
        "options": [
          "Not confident at all: I need to learn more",
          "Somewhat confident: I know the basics",
          "Confident: I practise safety consistently",
          "Very confident: I can teach others"
        ],
        "section": "Safety & hygiene"
      },
      {
        "id": "q5a_commitment",
        "label": "Name ONE specific skill you will work on this week.",
        "type": "textarea",
        "required": true,
        "section": "My commitment"
      },
      {
        "id": "q5b_improvement",
        "label": "How will you know you have improved? What will be different in your work?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      },
      {
        "id": "q5c_cross_trade",
        "label": "Which skill from another trade area surprised or impressed you today?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      }
    ]
  },
  {
    "id": "worksheet-05-cosmetology",
    "title": "Cosmetology",
    "description": "Cosmetology is the professional skill of caring for skin, applying make-up, and performing beauty treatments in a way that is safe, clean, and suited to each client's needs.",
    "sortOrder": 5,
    "published": true,
    "questions": [
      {
        "id": "master_name",
        "label": "Your master's name",
        "type": "text",
        "required": false,
        "section": "About you"
      },
      {
        "id": "q1_definition",
        "label": "In your own words, explain what Cosmetology means. Why does it matter to do it well?",
        "type": "textarea",
        "required": true,
        "section": "Definition",
        "context": "Cosmetology is the professional skill of caring for skin, applying make-up, and performing beauty treatments in a way that is safe, clean, and suited to each client's needs."
      },
      {
        "id": "q2a_skills_checked",
        "label": "Which of these skills do you already practise in your workshop? Select all that apply.",
        "type": "checkbox",
        "required": false,
        "options": [
          "Skin Type Assessment",
          "Hygiene & Tool Sanitation",
          "Foundation & Colour Matching",
          "Skin & Facial Treatments"
        ],
        "section": "Technical skills"
      },
      {
        "id": "q2b_skill_practice",
        "label": "Choose ONE skill you selected above and describe exactly how you do it in your workshop.",
        "type": "textarea",
        "required": true,
        "section": "Technical skills"
      },
      {
        "id": "q3_scenario",
        "label": "What is your answer? Name the skill that failed and explain what the correct approach should be.",
        "type": "textarea",
        "required": true,
        "section": "Apply your knowledge",
        "context": "You apply a foundation to a client's face. Thirty minutes later, her skin is red and itchy in certain areas. What likely caused this, and what skill should have prevented it?"
      },
      {
        "id": "q4_safety",
        "label": "A client tells you she has very sensitive skin. What two things should you do BEFORE applying any product to her face?",
        "type": "textarea",
        "required": true,
        "section": "Safety & hygiene"
      },
      {
        "id": "q4_confidence",
        "label": "How confident are you with the safety practices in your trade right now?",
        "type": "radio",
        "required": false,
        "options": [
          "Not confident at all: I need to learn more",
          "Somewhat confident: I know the basics",
          "Confident: I practise safety consistently",
          "Very confident: I can teach others"
        ],
        "section": "Safety & hygiene"
      },
      {
        "id": "q5a_commitment",
        "label": "Name ONE specific skill you will work on this week.",
        "type": "textarea",
        "required": true,
        "section": "My commitment"
      },
      {
        "id": "q5b_improvement",
        "label": "How will you know you have improved? What will be different in your work?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      },
      {
        "id": "q5c_cross_trade",
        "label": "Which skill from another trade area surprised or impressed you today?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      }
    ]
  },
  {
    "id": "worksheet-06-auto-mechanics",
    "title": "Auto Mechanics",
    "description": "Auto Mechanics is the skill of diagnosing, repairing, and maintaining vehicles, including engines, brakes, electrical systems, and body parts, so they run safely and well.",
    "sortOrder": 6,
    "published": true,
    "questions": [
      {
        "id": "master_name",
        "label": "Your master's name",
        "type": "text",
        "required": false,
        "section": "About you"
      },
      {
        "id": "q1_definition",
        "label": "In your own words, explain what Auto Mechanics means. Why does it matter to do it well?",
        "type": "textarea",
        "required": true,
        "section": "Definition",
        "context": "Auto Mechanics is the skill of diagnosing, repairing, and maintaining vehicles, including engines, brakes, electrical systems, and body parts, so they run safely and well."
      },
      {
        "id": "q2a_skills_checked",
        "label": "Which of these skills do you already practise in your workshop? Select all that apply.",
        "type": "checkbox",
        "required": false,
        "options": [
          "Engine Diagnosis",
          "Fluid Checks & Changes",
          "Brake System",
          "Electrical & Wiring"
        ],
        "section": "Technical skills"
      },
      {
        "id": "q2b_skill_practice",
        "label": "Choose ONE skill you selected above and describe exactly how you do it in your workshop.",
        "type": "textarea",
        "required": true,
        "section": "Technical skills"
      },
      {
        "id": "q3_scenario",
        "label": "What is your answer? Name the skill that failed and explain what the correct approach should be.",
        "type": "textarea",
        "required": true,
        "section": "Apply your knowledge",
        "context": "A car is brought in with the complaint: 'the brakes feel soft and the car takes too long to stop.' Using what you learned today, what would you check first and in what order?"
      },
      {
        "id": "q4_safety",
        "label": "Before working on any electrical component in a vehicle, what is the first thing you must always do and why?",
        "type": "textarea",
        "required": true,
        "section": "Safety & hygiene"
      },
      {
        "id": "q4_confidence",
        "label": "How confident are you with the safety practices in your trade right now?",
        "type": "radio",
        "required": false,
        "options": [
          "Not confident at all: I need to learn more",
          "Somewhat confident: I know the basics",
          "Confident: I practise safety consistently",
          "Very confident: I can teach others"
        ],
        "section": "Safety & hygiene"
      },
      {
        "id": "q5a_commitment",
        "label": "Name ONE specific skill you will work on this week.",
        "type": "textarea",
        "required": true,
        "section": "My commitment"
      },
      {
        "id": "q5b_improvement",
        "label": "How will you know you have improved? What will be different in your work?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      },
      {
        "id": "q5c_cross_trade",
        "label": "Which skill from another trade area surprised or impressed you today?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      }
    ]
  },
  {
    "id": "worksheet-07-carpentry-furniture",
    "title": "Carpentry & Furniture",
    "description": "Carpentry and Furniture Making is the skill of cutting, shaping, joining, and finishing wood and other materials to produce furniture, doors, and structures that are strong and well-crafted.",
    "sortOrder": 7,
    "published": true,
    "questions": [
      {
        "id": "master_name",
        "label": "Your master's name",
        "type": "text",
        "required": false,
        "section": "About you"
      },
      {
        "id": "q1_definition",
        "label": "In your own words, explain what Carpentry & Furniture means. Why does it matter to do it well?",
        "type": "textarea",
        "required": true,
        "section": "Definition",
        "context": "Carpentry and Furniture Making is the skill of cutting, shaping, joining, and finishing wood and other materials to produce furniture, doors, and structures that are strong and well-crafted."
      },
      {
        "id": "q2a_skills_checked",
        "label": "Which of these skills do you already practise in your workshop? Select all that apply.",
        "type": "checkbox",
        "required": false,
        "options": [
          "Measuring & Marking",
          "Cutting & Shaping",
          "Joinery (Joining Wood)",
          "Sanding & Finishing"
        ],
        "section": "Technical skills"
      },
      {
        "id": "q2b_skill_practice",
        "label": "Choose ONE skill you selected above and describe exactly how you do it in your workshop.",
        "type": "textarea",
        "required": true,
        "section": "Technical skills"
      },
      {
        "id": "q3_scenario",
        "label": "What is your answer? Name the skill that failed and explain what the correct approach should be.",
        "type": "textarea",
        "required": true,
        "section": "Apply your knowledge",
        "context": "You cut a plank of wood for a wardrobe door. When you assemble it, the door is 4cm too short and the edge is rough and splintered. Which two skills failed, and what would you do differently?"
      },
      {
        "id": "q4_safety",
        "label": "What personal protective equipment (PPE) should a carpenter wear when cutting wood, and why?",
        "type": "textarea",
        "required": true,
        "section": "Safety & hygiene"
      },
      {
        "id": "q4_confidence",
        "label": "How confident are you with the safety practices in your trade right now?",
        "type": "radio",
        "required": false,
        "options": [
          "Not confident at all: I need to learn more",
          "Somewhat confident: I know the basics",
          "Confident: I practise safety consistently",
          "Very confident: I can teach others"
        ],
        "section": "Safety & hygiene"
      },
      {
        "id": "q5a_commitment",
        "label": "Name ONE specific skill you will work on this week.",
        "type": "textarea",
        "required": true,
        "section": "My commitment"
      },
      {
        "id": "q5b_improvement",
        "label": "How will you know you have improved? What will be different in your work?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      },
      {
        "id": "q5c_cross_trade",
        "label": "Which skill from another trade area surprised or impressed you today?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      }
    ]
  },
  {
    "id": "worksheet-08-photography",
    "title": "Photography",
    "description": "Photography is the skill of using a camera, phone or professional, to capture clear, well-composed, and properly lit images that tell a story or serve a client's purpose.",
    "sortOrder": 8,
    "published": true,
    "questions": [
      {
        "id": "master_name",
        "label": "Your master's name",
        "type": "text",
        "required": false,
        "section": "About you"
      },
      {
        "id": "q1_definition",
        "label": "In your own words, explain what Photography means. Why does it matter to do it well?",
        "type": "textarea",
        "required": true,
        "section": "Definition",
        "context": "Photography is the skill of using a camera, phone or professional, to capture clear, well-composed, and properly lit images that tell a story or serve a client's purpose."
      },
      {
        "id": "q2a_skills_checked",
        "label": "Which of these skills do you already practise in your workshop? Select all that apply.",
        "type": "checkbox",
        "required": false,
        "options": [
          "Camera Settings (Exposure)",
          "Composition & Framing",
          "Lighting",
          "Editing & Delivery"
        ],
        "section": "Technical skills"
      },
      {
        "id": "q2b_skill_practice",
        "label": "Choose ONE skill you selected above and describe exactly how you do it in your workshop.",
        "type": "textarea",
        "required": true,
        "section": "Technical skills"
      },
      {
        "id": "q3_scenario",
        "label": "What is your answer? Name the skill that failed and explain what the correct approach should be.",
        "type": "textarea",
        "required": true,
        "section": "Apply your knowledge",
        "context": "You take portraits of a client outdoors at 1pm. When you review the photos, the faces look dark with harsh shadows under the nose and eyes. What caused this, and how would you fix it next time?"
      },
      {
        "id": "q4_safety",
        "label": "A client pays for 50 edited photos from an event. When you deliver the files, the client says they cannot open them. What should you have done before delivery to prevent this?",
        "type": "textarea",
        "required": true,
        "section": "Safety & hygiene"
      },
      {
        "id": "q4_confidence",
        "label": "How confident are you with the safety practices in your trade right now?",
        "type": "radio",
        "required": false,
        "options": [
          "Not confident at all: I need to learn more",
          "Somewhat confident: I know the basics",
          "Confident: I practise safety consistently",
          "Very confident: I can teach others"
        ],
        "section": "Safety & hygiene"
      },
      {
        "id": "q5a_commitment",
        "label": "Name ONE specific skill you will work on this week.",
        "type": "textarea",
        "required": true,
        "section": "My commitment"
      },
      {
        "id": "q5b_improvement",
        "label": "How will you know you have improved? What will be different in your work?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      },
      {
        "id": "q5c_cross_trade",
        "label": "Which skill from another trade area surprised or impressed you today?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      }
    ]
  },
  {
    "id": "worksheet-09-hair-making",
    "title": "Hair Making",
    "description": "Hair Making is the professional skill of washing, treating, styling, braiding, or weaving natural and artificial hair to create neat, long-lasting styles that suit the client.",
    "sortOrder": 9,
    "published": true,
    "questions": [
      {
        "id": "master_name",
        "label": "Your master's name",
        "type": "text",
        "required": false,
        "section": "About you"
      },
      {
        "id": "q1_definition",
        "label": "In your own words, explain what Hair Making means. Why does it matter to do it well?",
        "type": "textarea",
        "required": true,
        "section": "Definition",
        "context": "Hair Making is the professional skill of washing, treating, styling, braiding, or weaving natural and artificial hair to create neat, long-lasting styles that suit the client."
      },
      {
        "id": "q2a_skills_checked",
        "label": "Which of these skills do you already practise in your workshop? Select all that apply.",
        "type": "checkbox",
        "required": false,
        "options": [
          "Scalp & Hair Assessment",
          "Washing & Conditioning",
          "Braiding & Weaving Techniques",
          "Chemical Services (Relaxers & Colour)"
        ],
        "section": "Technical skills"
      },
      {
        "id": "q2b_skill_practice",
        "label": "Choose ONE skill you selected above and describe exactly how you do it in your workshop.",
        "type": "textarea",
        "required": true,
        "section": "Technical skills"
      },
      {
        "id": "q3_scenario",
        "label": "What is your answer? Name the skill that failed and explain what the correct approach should be.",
        "type": "textarea",
        "required": true,
        "section": "Apply your knowledge",
        "context": "After applying a relaxer, a client's hair breaks off in several places along the shaft. Based on what you learned today, what most likely caused this damage?"
      },
      {
        "id": "q4_safety",
        "label": "A client wants a hair colour treatment. What must you do 24–48 hours before applying the colour, and why is this step not optional?",
        "type": "textarea",
        "required": true,
        "section": "Safety & hygiene"
      },
      {
        "id": "q4_confidence",
        "label": "How confident are you with the safety practices in your trade right now?",
        "type": "radio",
        "required": false,
        "options": [
          "Not confident at all: I need to learn more",
          "Somewhat confident: I know the basics",
          "Confident: I practise safety consistently",
          "Very confident: I can teach others"
        ],
        "section": "Safety & hygiene"
      },
      {
        "id": "q5a_commitment",
        "label": "Name ONE specific skill you will work on this week.",
        "type": "textarea",
        "required": true,
        "section": "My commitment"
      },
      {
        "id": "q5b_improvement",
        "label": "How will you know you have improved? What will be different in your work?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      },
      {
        "id": "q5c_cross_trade",
        "label": "Which skill from another trade area surprised or impressed you today?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      }
    ]
  },
  {
    "id": "worksheet-10-catering",
    "title": "Catering",
    "description": "Catering is the skill of planning, preparing, cooking, presenting, and serving food safely and professionally for individuals or groups, whether at events or in a food business.",
    "sortOrder": 10,
    "published": true,
    "questions": [
      {
        "id": "master_name",
        "label": "Your master's name",
        "type": "text",
        "required": false,
        "section": "About you"
      },
      {
        "id": "q1_definition",
        "label": "In your own words, explain what Catering means. Why does it matter to do it well?",
        "type": "textarea",
        "required": true,
        "section": "Definition",
        "context": "Catering is the skill of planning, preparing, cooking, presenting, and serving food safely and professionally for individuals or groups, whether at events or in a food business."
      },
      {
        "id": "q2a_skills_checked",
        "label": "Which of these skills do you already practise in your workshop? Select all that apply.",
        "type": "checkbox",
        "required": false,
        "options": [
          "Food Hygiene & Safety",
          "Mise en Place (Prep Before Cooking)",
          "Cooking Techniques",
          "Presentation & Portioning"
        ],
        "section": "Technical skills"
      },
      {
        "id": "q2b_skill_practice",
        "label": "Choose ONE skill you selected above and describe exactly how you do it in your workshop.",
        "type": "textarea",
        "required": true,
        "section": "Technical skills"
      },
      {
        "id": "q3_scenario",
        "label": "What is your answer? Name the skill that failed and explain what the correct approach should be.",
        "type": "textarea",
        "required": true,
        "section": "Apply your knowledge",
        "context": "Three guests at an event become ill after eating the food you prepared. The health inspector visits and finds that raw chicken was stored on the shelf above ready-to-eat salad in the fridge. Which skill failed, and what is the correct practice?"
      },
      {
        "id": "q4_safety",
        "label": "You are cooking for 50 people at an event. Name TWO hygiene practices you must follow throughout the entire cooking process.",
        "type": "textarea",
        "required": true,
        "section": "Safety & hygiene"
      },
      {
        "id": "q4_confidence",
        "label": "How confident are you with the safety practices in your trade right now?",
        "type": "radio",
        "required": false,
        "options": [
          "Not confident at all: I need to learn more",
          "Somewhat confident: I know the basics",
          "Confident: I practise safety consistently",
          "Very confident: I can teach others"
        ],
        "section": "Safety & hygiene"
      },
      {
        "id": "q5a_commitment",
        "label": "Name ONE specific skill you will work on this week.",
        "type": "textarea",
        "required": true,
        "section": "My commitment"
      },
      {
        "id": "q5b_improvement",
        "label": "How will you know you have improved? What will be different in your work?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      },
      {
        "id": "q5c_cross_trade",
        "label": "Which skill from another trade area surprised or impressed you today?",
        "type": "textarea",
        "required": false,
        "section": "My commitment"
      }
    ]
  }
] as Assignment[]
